# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

# A docker container will be used to build and test the app, which will then be uploaded to the Azure Container Registry (ACR)
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Sufi ACR Private Registery'
        repository: 'Awesome-API'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)

        
