---
- hosts: all
  gather_facts: false
  become: yes
  vars:
    docker_compose_version: "1.27.4"
  roles:
  - docker  # Installs Docker dependencies 

  tasks:
    - name: Log into Azure Container Registery (ACR)
      community.docker.docker_login:
        registry_url: "{{ lookup('env','Registery') }}"
        username: "{{ lookup('env','username') }}"
        password: "{{ lookup('env','pass') }}"
        reauthorize: yes

    - name: Pull the Image from ACR
      docker_image:
        name: awesome-api:latest

    - name: Start Container
      docker_container:
       name: webserver
       state: present
       image: awesome-api:"{{ lookup('env','build') }}"
       expose: 80

    - name: Ensure Container is Running
      docker_container:
       name: webserver
       image: awesome-api:latest
       state: started
       expose: 80
